name: Deploy CDK App to Multiple Accounts

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read      

jobs:
  synthesize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install AWS CDK and Utilities
        run: |
          npm install -g aws-cdk@latest
          sudo apt-get update && sudo apt-get install -y jq

      - name: Install Snyk CLI
        run: npm install -g snyk
      
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: CDK Synthesize
        run: |
          source .venv/bin/activate
          cdk synth

      - name: Save list of YAML files
        id: yaml_files
        run: |
          ls iamConfigs/*.yaml | xargs -n 1 basename | sed 's/iamrole-//;s/.yaml//' > yaml_files.txt
          echo "yaml_files=$(cat yaml_files.txt)" >> $GITHUB_ENV

  deploy:
    needs: synthesize
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account_id: ${{ fromJson(env.yaml_files) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials using OIDC Identity
        uses: aws-actions/configure-aws-credentials@v4
        with:
           role-to-assume: arn:aws:iam::${{ matrix.account_id }}:role/GitHubActionsRole
           role-session-name: OIDC-GitHubActionsRole
           aws-region: us-east-1    
           audience: sts.amazonaws.com
           role-duration-seconds: 3600
          
      - name: Deploy CDK Stack
        run: |
          set -e
          source .venv/bin/activate
          
          stack_name="IamRoleConfigStack-${{ matrix.account_id }}"
          cdk deploy $stack_name --require-approval never --context file=iamConfigs/iamrole-${{ matrix.account_id }}.yaml
